behaviors:
  RobotAgent:
    trainer_type: ppo
    
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 3.0e-5           # 降低學習率以增加訓練穩定性
      learning_rate_schedule: linear
      
      beta: 5.0e-3
      beta_schedule: linear
      
      epsilon: 0.2
      epsilon_schedule: linear

      lambd: 0.95
      num_epoch: 3
      
      #max_norm: 1.0                   # 新增梯度裁剪，防止數值不穩定

    network_settings:
      normalize: true                 # 確保開啟正規化以獲得更好效能
      hidden_units: 256
      num_layers: 3
      
      memory:
        sequence_length: 64
        memory_size: 128

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      
      curiosity:
        strength: 0.02
        gamma: 0.99
        network_settings:
          hidden_units: 128
          num_layers: 2
          
    max_steps: 100000000
    time_horizon: 1000
    summary_freq: 20000
    checkpoint_interval: 500000
    threaded: true